### ISSUE TITLE
Clickable zone of the second row in last used emoji panel

### ISSUE THREAD

**Issue by eugene-lazarev** [zhukov/webogram#717]
SUBJ.

Look at this:

![1](https://cloud.githubusercontent.com/assets/1990392/6390625/facefdda-bdbe-11e4-8a62-98790831efdb.png)

Macbook Pro mid2012 (non-retina), Mac OS X 10.10.2, Chrome 40.0.2214.115

**Comment by ArtemFitiskin** [comment]
So cute :bug: 

I think that one of possible solution is: 

### Change padding in desktop.css 

```css
.composer_emoji_panel a {
  ...
  padding: 5px;
  ...
}
```

to

```css
.composer_emoji_panel a {
  ...
  padding: 4px 5px 6px 5px;
  ...
}
```

### Remove margin-top in app.css

```css
a.composer_emoji_btn {
  margin: -1px 0 0 -1px;
  ...
}
```

to 

```css
a.composer_emoji_btn {
  margin: 0 0 0 -1px;
  ...
}
```

Works fine for me, but need a review.
