### ISSUE TITLE
Don't limit the max-width on the desktop?

### ISSUE THREAD

**Issue by sulami** [zhukov/webogram#861]
When running webogram in fullscreen on a reasonably size screen, it wastes a lot of space on the sides because the wrapper widths are limited to 1010px. At the same time, the actual message content is less than 400px wide, which makes longer messages unnecessarily tall, so that you have to scroll a lot more. Something like

```css
div.tg_head_split { max-width: calc(100% - 50px) !important; }
div.im_page_wrap { max-width: calc(100% - 50px) !important; }
div.im_message_wrap { max-width: calc(100% - 100px) !important; }
div.im_send_panel_wrap { max-width: calc(100% - 115px) !important; }
form.im_send_form { max-width: 100% !important; }
```
in a userstyle already makes the page look a lot better on desktops imho, while breaking nothing as far as I can see. Any thoughts on this? This would be quite an easy fix, if you want me to, I would even write a pull request myself.
