### ISSUE TITLE
Preserve whitespaces in messages

### ISSUE THREAD

**Issue by maximal** [zhukov/webogram#930]
It’s better to preserve whitespaces in messages, like phone applications do.

Something like
```css
.message {
	white-space: pre-wrap;
}
```
should work.

**Comment by yuriteixeira** [comment]
The PR that fixes the problem was already sent. Any reasons to not merge it?

**Comment by maximal** [comment]
Seems like the author is away at the moment.

**Comment by yuriteixeira** [comment]
@maximal: check [this](https://github.com/yuriteixeira/webogram/commit/0d1345e6d599224650e86f57d6fd938424e8ca69) to see the discussion

**Comment by maximal** [comment]
@yuriteixeira, I guess, it was adressed to @zhukov…

**Comment by zhukov** [comment]
Spaces are trimmed server-side, when sending.
No plans to uncollapse spaces inside messages when displaying.

**Comment by maximal** [comment]
Hmmm. Why do they preserved in android application then?

![Whitespaces in Telegram](https://cloud.githubusercontent.com/assets/980679/12975558/c1fa1f58-d0cd-11e5-89c0-5e1ba05a6961.png)

**Comment by maximal** [comment]
Thanks to @alex-mos:

```css
.im_message_text {
	word-wrap: break-word;
	line-height: 150%;
	white-space: pre-wrap;
}
```
